stages:
  - deploy

production:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev git
  - gem install dpl
  - dpl --provider=heroku --app=fitshare-backend --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - master
